##
## EPITECH PROJECT, 2019
## TRADE_2018
## File description:
## Makefile
##

SRC	=	main.py	\
		src/Bot.py

NAME	=	trade.zip

all	:	$(NAME)

$(NAME)	:
	@zip -r trade.zip $(SRC)

fclean	:
	rm -rf $(NAME)

re	:	fclean all