##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## By Oscar
##

#ifndef _MAKE_
#define _MAKE_

SRC =	exercice1.c



NAME =	JERUSALEM

all:	$(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC) -l "c_graph_prog"

clean:
	rm -f *.o

fclean:	clean

	rm -f $(NAME)

re:	fclean all

#endif
