##
## EPITECH PROJECT, 2017
## rush3
## File description:
## makefile
##

#ifdef _MAKE_
#define _MAKE_

NAME = rush3

all :
	gcc *.c -o $(NAME) -L lib/my/ -lmy

clean :
	rm *.o

fclean :
	rm $(NAME)

re : fclean all


#endif
