##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## By Luis Angel Macias de la Cruz
##

#ifndef _MAKE_
#define _MAKE_


NAME =	calc

all:
	gcc *.c -o $(NAME)
clean:
	rm  -f *.o
fclean:	 clean
	rm $(NAME)
re:	fclean all

#endif
