/*
** EPITECH PROJECT, 2019
** epitech
** File description:
** by oriol
*/

#include "list.h"

prototype_t g_syscalls[] =
{
    { "read", 3, { "int", "char *", "size_t" }, "ssize_t" },
    { "write", 3, { "int", "char *", "size_t" }, "ssize_t" },
    { "open", 2, { "char *", "int" }, "int" },
    { "close", 1, { "int" }, "int" },
    { "stat", 2, { "char *", "struct stat *" }, "int" },
    { "fstat", 2, { "int", "struct stat *" }, "int" },
    { "lstat", 2, { "char *", "struct stat *" }, "int" },
    { "poll", 3, { "struct pollfd *", "nfds_t", "int" }, "int" },
    { "lseek", 3, { "int", "off_t", "int" }, "off_t" },
    { "mmap", 6, { "void *", "size_t", "int", "int", "int", "off_t" },
      "void *" },
    { "mprotect", 3, { "void *", "size_t", "int" }, "int" },
    { "munmap", 2, { "void *", "size_t" }, "int" },
    { "brk", 1, { "int" }, "void *" },
    { "sigaction", 3,
     { "int", "struct sigaction *", "struct sigaction *" }, "int" },
    { "sigprocmask", 3, { "int", "sigset_t *", "sigset_t *" }, "int" },
    { "sigreturn", 1, { "unsigned long" }, "int" },
    { "ioctl", 2, { "int", "int" }, "int" },
    { "pread64", 4, { "int", "void *", "size_t", "off_t" }, "ssize_t" },
    { "pwrite64", 4, { "int", "void *", "size_t", "off_t" }, "ssize_t" },
    { "readv", 3, { "int", "struct  iovec *", "int" }, "ssize_t" },
    { "writev", 3, { "int", "struct  iovec *", "int" }, "ssize_t" },
    { "access", 2, { "char *", "int" }, "int" },
    { "pipe", 1, { "int[2]" }, "int" },
    { "select", 5,
     { "int", "fd_set *", "fd_set *", "fd_set *", "stuct timeval *" }, "int" },
    { "sched_yield", 0, { "void" }, "int" },
    { "mremap", 4, { "void *", "size_t", "size_t", "int" }, "void *" },
    { "msync", 3, { "void *", "size_t", "int" }, "int" },
    { "mincore", 3, { "void *", "size_t", "unsigned char *" }, "int" },
    { "madvise", 3, { "void *", "size_t", "int" }, "int" },
    { "shmget", 3, { "key_t", "size_t", "int" }, "int" },
    { "shmat", 3, { "int", "void *", "int" }, "void *" },
    { "shmctl", 3, { "int", "int", "struct shmid_ds *" }, "int" },
    { "dup", 1, { "int" }, "int" },
    { "dup2", 2, { "int", "int" }, "int" },
    { "pause", 0, { "void" }, "int" },
    { "nanosleep", 2, { "struct timespec *", "struct timespec *" }, "int" },
    { "getitimer", 2, { "int", "struct itimervalq *" }, "int" },
    { "alarm", 1, { "unsigned int" }, "unsigned int" },
    { "setitimer", 3,
     { "int", "struct itimerval *", "struct itimerval *" }, "int" },
    { "getpid", 0, { "void""void" }, "pid_t" },
    { "sendfile", 4, { "int", "int", "off_t *", "size_t" }, "ssize_t" },
    { "socket", 3, { "int", "int", "int" }, "int" },
    { "connect", 3, { "int", "struct sockaddr *", "socklen_t" }, "int" },
    { "accept", 3, { "int", "struct sockaddr *", "socklen_t" }, "int" },
    { "sendto", 6,
     { "int", "void *", "size_t", "int",
      "struct sockaddr *", "socklen_t" }, "ssize_t" },
    { "recvfrom", 6,
     { "int", "void *", "size_t", "int", "struct sockaddr *", "socklen_t *" },
     "ssize_t" },
    { "sendmsg", 3, { "int", "struct msghdr *", "int" }, "ssize_t" },
    { "recvmsg", 3, { "int", "struct msghdr *", "int" }, "ssize_t" },
    { "shutdown", 2, { "int", "int" }, "int" },
    { "bind", 3, { "int", "struct sockaddr *", "socklen_t" }, "int" },
    { "listen", 2, { "int", "int" }, "int" },
    { "getsockname", 3, { "int", "struct sockaddr *", "socklen_t *" }, "int" },
    { "getpeername", 3, { "int", "struct sockaddr *", "socklen_t *" }, "int" },
    { "socketpair", 4, { "int", "int", "int", "int[2]" }, "int" },
    { "setsockopt", 5, { "int", "int", "int", "void *", "socklen_t" },
     "int" },
    { "getsockopt", 5, { "int", "int", "int", "void *", "socklen_t" }, "int" },
    { "clone", 2, { "int *", "struct stat *" }, "int" },
    { "fork", 0, { "void" }, "pid_t" },
    { "vfork", 0, { "void" }, "pid_t" },
    { "execve", 3,
      { "char *", "char **", "char **" }, "int" },
    { "END", 3,
      { "char *", "char **", "char **" }, "int" },
};
