#! /usr/bin/env python3
from __future__ import print_function
import sys
import math

class storage(object):
    ax = 0
    ay = 0
    axy = 0
    squareOfx = 0
    squareOfy = 0
    val = 0
    Year = 1960





def countries(argv):
    lenght = len(argv)
    


def help():
    print("USAGE")
    print("\t./207demography code [...]\n")
    print("DESCRIPITON")
    print("\tu\tcode")
    print("\ts\tcountry code")        

if __name__ == "__main__":
    try:
        if len(sys.argv) == 1:
          exit(84)
        if len(sys.argv) == 2 and sys.argv[1] == "-h":
            help()
        elif len(sys.argv) >= 3 and sys.argv[1] != "-h":
            countries(sys.argv)
        else:
            exit(84)
    except Exception as e:
        exit(84)
    exit(0)