##
## EPITECH PROJECT, 2019
## OOP_arcade_2018
## File description:
## Makefile
##

SRC	=	test.cpp

NAME	=	unit_tests

all:
	g++ -o $(NAME) $(SRC) --coverage -lcriterion -ldl
fclean:
	rm -rf *~ *# *.gcno *.gcda $(NAME)

